### ISSUE TITLE
Cool project

### ISSUE THREAD

**Issue by lostpebble** [petehunt/use-state-singleton#1]
Hi Pete!

I've been following your dev stuff for quite some time now (since the old React days). Just noticed that you put this project together and thought I'd drop in and say hi. I've actually been working on something coincidentally _very_ similar! Its cool to see you implement it too - might be silly but its a nice validation for a somewhat small-fry dev like myself.

You can check it out here: https://lostpebble.github.io/pullstate/docs/quick-example

Just thought it might interest you. Perhaps some of the extras that have been progressively added over the last year as I've built it and used it in my own projects might interest you too. Would of course love to have you as a contributor - and combine our efforts - but perhaps its a bit over the top to what your current requirements are. Overall this state updating / re-rendering with immer part is very simple and often that's all you need.

**Comment by petehunt** [comment]
ah at first glance it looks very similar and much more polished :) i'll try to dig into this later today -- this project was a weekend hack for me and hasn't really been tried on a real app yet :)

**Comment by lostpebble** [comment]
Okay cool :) Yea, I've been "dogfooding" it for a while now in my own projects so there's plenty of added stuff beyond simple state stores now, its been expanded it into async state situations too. Kinda just wanted one thing to handle all state concerns.

I'm at the point where I'd like to go back and refactor / simplify some of the code and perhaps split out the different parts into separate modules (perhaps some adapters for other view libraries), along with some extra utilities for things like undo / redo, store to LocalStorage synchronization etc.

Anyway, hope you find some use in it :)

**Comment by petehunt** [comment]
i added a note to the readme that use-state-singleton isn't used in prod, and i also added a link to Pullstate as an alternative. overall i like pullstate but the async stuff is more than i'm looking for right now :) gonna close this issue out unless there's anything else -- thanks for sharing a great project!

**Comment by lostpebble** [comment]
Okay cool, appreciate the link, and much thanks for the kind words! All the best with your future projects, will be sure to continue keeping an eye out :)
